version: '3'
services:
  api:
    container_name: process_monitor 
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

networks:
  backend:
    driver: bridge

volumes:
  mongodata: